// <auto-generated />
using System;
using IoTEx.WaternetIoT.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;


#nullable disable

namespace Waternet.DAL.Migrations.OADB
{
    [DbContext(typeof(OADBContext))]
    [Migration("20220918183238_OA_V2")]
    partial class OA_V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Waternet.IoT.Portal.Models.OAMessageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("AssetUID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ASSET_UID");

                    b.Property<Guid?>("DeviceBatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DEVICE_BATCH_ID");

                    b.Property<string>("DeviceBatchName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DEVICE_BATCH_NAME");

                    b.Property<Guid>("DeviceID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DEVICE_ID");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DEVICE_NAME");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DEVICE_TYPE_ID");

                    b.Property<string>("DeviceTypeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DEVICE_TYPE_NAME");

                    b.Property<DateTime>("EVT_DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("EVT_DATE");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EVT_NAME");

                    b.Property<string>("EventUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EVT_UNIT");

                    b.Property<double>("EventValue")
                        .HasColumnType("float")
                        .HasColumnName("EVT_VALUE");

                    b.Property<string>("IMEI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IMEI");

                    b.Property<double>("Lat")
                        .HasColumnType("float")
                        .HasColumnName("LAT");

                    b.Property<double>("Long")
                        .HasColumnType("float")
                        .HasColumnName("LNG");

                    b.Property<string>("PC")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PC_NAME");

                    b.Property<string>("PCUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PC_UNIT");

                    b.Property<string>("PCValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PC_VALUE");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PROJECT");

                    b.HasKey("Id");

                    b.ToTable("OA_MESSAGE");
                });
#pragma warning restore 612, 618
        }
    }
}
