using System;
using System.Collections.Generic;
using System.Text;
using IoTEx.WaternetIoT.Data.Model;
using IoTEx.WaternetIoT.Model.DTOs;
using IoTEx.WaternetIoT.Model.DTOs.API;
using Newtonsoft.Json;

namespace IoTEx.Waternet.Parser
{
    public class PULSE_V1_PARSER : IOT_DEVICE_GENERIC_V2_PARSER
    {
        public override string Version
        {
            get { return "1.0.0"; }
        }
        public override APIResultDTO<string> GenerateConfigureDeviceMessage(List<DeviceDefinitionConfigurationDTO> configs)
        {
            return new APIResultDTO<string>() { IsOk = false, Error = "NO CONFIGURATION MESSAGE DEFINED" };
        }
        public override List<DeviceDefinitionConfigurationDTO> GetDeviceTypeConfigurationItems()
        {
            List<DeviceDefinitionConfigurationDTO> configs = new List<DeviceDefinitionConfigurationDTO>();
            configs.Add(new DeviceDefinitionConfigurationDTO() { name = "Multiplier", description = "This multiplier is used to multiply the counter generated by the pulse", symbol = "mx=", value = "1", type = DeviceDefinitionConfigurationDTO.ConfigurationTypeEnum.type_double });
            
            return configs;
        }
        public override void Definition()
        {
            int sensorType = (int)SENSOR_TYPE_ENUM.SENSOR_PULSE;
            IoTDataDefineMemberExt(0, sensorType, 1, "Counter", 2, "", 1, 5);
            IoTDataDefineMemberExt(0, sensorType, 2, "Delta", 2, "", 1, 5);
        }
        public override void AddPostEvent(DeviceMessageDTO message, DeviceDefinitionDTO deviceInfo)
        {
            

        }
    }
}


